
name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install deps (PM)
        run: |
          python -m pip install --upgrade pip
          pip install -r predictive_maintenance/requirements.txt
      - name: Run PM training (quick)
        run: python predictive_maintenance/train_pm.py
